<a href="https://colab.research.google.com/github/alekya34/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,5,6,7])
print(a)
print(type(a))

[1 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
# zero dimensional array
b=np.array(20)
print(b)
print(type(b))

20
<class 'numpy.ndarray'>


In [ ]:
#  two dimensional
c=np.array([[1,4],[9,7]])
print(c)
d=np.array([[[1,4],[3,5],[9,5]]])
print(d)
# to know the dimension we use ndim method
print(d.ndim)

[[1 4]
 [9 7]]
[[[1 4]
  [3 5]
  [9 5]]]
3


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)

[5 7 9]


In [ ]:
#to generate random number
from numpy import random
x=random.randint(1000)
print(x)

391


In [ ]:
y=random.rand()
print(y)

0.2365579838286207


In [ ]:
#to generate random array
x1=random.randint(100,size=(5))
print(x1)

[ 8 97 93 57 34]


In [ ]:
#to generate random 2 dimensional array
x2=random.randint(100,size=(2,5))
print(x2)

[[ 7 46  4 48 92]
 [94 77 56 71  3]]


In [ ]:
r=random.choice([3,5,6,2])
print(r)

2


In [ ]:
r=random.choice([4,8,6,23,0],size=(5))
print(r)

[6 0 6 6 4]


In [ ]:
r=random.choice([7,6,4,90,67],size=(3,2,7))
print(r)

[[[ 7 67  4  4  7  4 90]
  [90  4 67  4 67  4  6]]

 [[ 7  6  4 67 67 90  4]
  [ 4 90  6  7  6 90  4]]

 [[90  6  7  4 90  4  7]
  [ 7  7  6 67 67 90  7]]]


In [ ]:
#universal function
a1=np.array([1,2,3])
a2=np.array([3,2,1])
add_result=np.add(a1,a2)
subtract_result=np.subtract(a1,a2)
multiply_result=np.multiply(a1,a2)
divide_result=np.divide(a1,a2)
print(add_result)
print(subtract_result)
print(multiply_result)
print(divide_result)

[4 4 4]
[-2  0  2]
[3 4 3]
[0.33333333 1.         3.        ]


In [13]:
arr=np.array([[1,2,3],[2,3,4]])
print(arr)
print(arr.shape)
print(arr.ndim)
arr=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [2 3 4]]
(2, 3)
2
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [14]:
arr=np.array([[[1,2,3],[1,2,3]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[1 2 3]
  [1 2 3]]]
(1, 2, 3)
3


In [15]:
#creating multidimensional arrays usinf ndmin
array=np.array([1,2,5,4],ndmin=5)
print(array)
print(array.ndim)#to know the dimensions

[[[[[1 2 5 4]]]]]
5


In [16]:
#indexing
arr=np.array([1,2,3,4,5])
print(arr[2])
print(arr[-1])

3
5


In [19]:
#indexing for 2 dimensional array
arr2d=np.array([[1,2,3],[4,7,5]])
print(arr2d[1,1])
print(arr2d[1,2])
print(arr2d[1,-1])

7
5
5


In [21]:
#boolean indexing
arr=np.array([1,2,3,4,5,6,7])
mask=arr>2
print(arr[mask])
print(mask)
indices=np.where(mask)
print(indices)

[3 4 5 6 7]
[False False  True  True  True  True  True]
(array([2, 3, 4, 5, 6]),)


In [ ]:
#slicing
a=np.array([1,2,6,3,2,2,5,6])
slice_result=a[2:6]
print(slice_result)


In [26]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])#first row
print(a[0,:])
print(a[:,-1])#last col
print(a[:,0])#first col
print(a[1:3,1:3])#sub matrix array[rowstart:rowend,colstart:colend]
print(a[::2, ::2])#arr[start:stop:step]


[1 2 3]
[1 2 3]
[3 6 9]
[1 4 7]
[[5 6]
 [8 9]]
[[1 3]
 [7 9]]


In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9])
slice_result=arr[1:9:2]
print(slice_result)

[2 4 6 8]


In [27]:
#Copy vs View
#copy-this one will not change the original array
original_array=np.array([1,2,3,4,5])
copied_array=original_array.copy()
copied_array[0]=10
print("original_array",original_array)
print("copied_array",copied_array)

original_array [1 2 3 4 5]
copied_array [10  2  3  4  5]


In [28]:
#view-this one will change the original array
original_array=np.array([1,2,3,4,5])
view_array=original_array.view()
view_array[0]=10
print("original_array",original_array)
print("view_array",view_array)

original_array [10  2  3  4  5]
view_array [10  2  3  4  5]


In [31]:
original_array=np.array([[1,2,3],[4,5,6]])
array_view=original_array.view()
array_view.shape=(6,1)
print("original Array")
print(original_array)
print("array_view")
print(array_view)
array_view.shape=(3,2)
print("original Array")
print(original_array)
print("array_view")
print(array_view)


original Array
[[1 2 3]
 [4 5 6]]
array_view
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
original Array
[[1 2 3]
 [4 5 6]]
array_view
[[1 2]
 [3 4]
 [5 6]]
